# Generated by Django 3.1 on 2021-12-26 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Comentarios activados/Comentarios desactivados')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
