# Generated by Django 3.1 on 2021-12-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211226_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Permitir comentarios'),
        ),
    ]
